[General]
showlogo=hidden
showClock=true
logo=/nix/store/6kvp3xmvi3lr1b5wr5gq7cngph8y2x5v-plasma-desktop-6.6.6/share/sddm/themes/breeze/default-logo.svg
type=image
color=#1d99f3
fontSize=10
background=/nix/store/khgyakz1mszjy7qsrr60x4azxz5s4zzb-breeze-6.6.6/share/wallpapers/Next/contents/images/5120x2880.png
needsFullUserModel=false
